
CREATE OR REPLACE FUNCTION FN_VALIDAR_USUARIO(IN USUARIO VARCHAR,IN PASS VARCHAR)  
RETURNS VARCHAR AS 

$body$
DECLARE

V_EMAIL VARCHAR;
V_PASSWORD VARCHAR;


BEGIN 


SELECT EMAIL,PASSWORD
INTO V_EMAIL, V_PASSWORD
FROM PROPIETARIO 
WHERE EMAIL = USUARIO;


	IF V_EMAIL = USUARIO AND V_PASSWORD = PASS THEN 
		RETURN 'Log-in Exitoso';
	ELSIF V_EMAIL ISNULL THEN 
		RETURN 'Usuario Incorrecto.';
	ELSIF V_PASSWORD <> PASS THEN 
		RETURN 'Password incorrecto.';
	ELSE
		RETURN 'Credenciales Incorrectas.';
	END IF;



END 
$body$
LANGUAGE plpgsql;	