
SELECT * FROM VW_LISTAR_REGIONES;
SELECT * FROM VW_LISTAR_PROVINCIAS;
SELECT * FROM VW_LISTAR_COMUNAS;


CREATE OR REPLACE VIEW VW_LISTAR_REGIONES AS
SELECT REGION_ID AS ID_REGION
      ,REGION_NOMBRE AS NOMBRE_REGION
	  ,REGION_ORDINAL AS REGION_ORDINAL
FROM REGIONES
ORDER BY REGION_ID ASC;

CREATE OR REPLACE VIEW VW_LISTAR_PROVINCIAS AS
SELECT P.PROVINCIA_ID AS ID_PROVINCIA
	  ,P.PROVINCIA_NOMBRE  AS NOMBRE_PROVINCIA
	  ,R.REGION_ID  AS ID_REGION	
FROM PROVINCIAS P
INNER JOIN REGIONES R
USING(REGION_ID)
ORDER BY P.PROVINCIA_ID ASC;

CREATE OR REPLACE VIEW VW_LISTAR_COMUNAS AS
SELECT C.COMUNA_ID AS ID_COMUNA
	  ,C.COMUNA_NOMBRE AS NOMBRE_COMUNA
	  ,P.PROVINCIA_ID AS ID_PROVINCIA
FROM COMUNAS C 
INNER JOIN PROVINCIAS P
USING (PROVINCIA_ID)
ORDER BY C.COMUNA_ID ASC;